export default {
    USER_LOADED: 'USER_LOADED',

    USER_ADD_AMOUNT: 'USER_ADD_AMOUNT',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    RESET_STATE: 'RESET_STATE'
}