export default {
    DEAL_LOADING: 'DEAL_LOADING',
    DEAL_LOADED: 'DEAL_LOADED',
    DEALS_LOAD_LIST: 'DEALS_LOAD_LIST',
    DEAL_CREATE: 'DEALT_CREATE',
    DEAL_LOAD_ONE: 'DEAL_LOAD_ONE',
    DEALT_SEND_MESSAGE: 'DEALT_SEND_MESSAGE',
    DEAL_STEP: 'DEAL_STEP',
    RESET_TARGET_ORDER: 'RESET_TARGET_ORDER',
    RESET_STATE: 'RESET_STATE'
}